"""Added likes column

Revision ID: 23801088f2e2
Revises: eceb64a8c27c
Create Date: 2025-03-25 18:08:58.101761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23801088f2e2'
down_revision = 'eceb64a8c27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('views')
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
