"""Add Review model

Revision ID: 39fbd18db15c
Revises: 2410b8d628ae
Create Date: 2025-03-25 23:52:44.545069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fbd18db15c'
down_revision = '2410b8d628ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key('fk_review_product_id', 'product', ['product_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_name')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
