"""Make review.user_id nullable

Revision ID: 76680c65a185
Revises: 80bc137f29f1
Create Date: 2025-03-26 00:18:47.470964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76680c65a185'
down_revision = '80bc137f29f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
