"""Add rating and points to Review

Revision ID: b2ba0b4dc5ef
Revises: 99d1ff99902a
Create Date: 2025-03-29 02:17:26.340466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ba0b4dc5ef'
down_revision = '99d1ff99902a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('points_awarded', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('points_awarded')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
